var cardArray = [  
"Skříplotina",
"Máslo komplikuje život!",
"A budeš/me se brodit v botech?",
"Incest",
"Šlápnutí na slimáka",
"Hlavně nebreč!",
"Byla jsem tu rychlejc než vy!",
"Pohlazení přes očičko",
"Skřetí běh",
"Jedině destiláty!",
"Výstřik do neznáma",
"Pojď se podívat na pavučinku!",
"Víte, co se stane, když okurka spadne do jámy?",
"Cítím se jako netopýří princezna!",
"Hele klokan a je bílej!",
"Já jsem kanadský ninja!",
"Myš Lenka",
"Hele poryv!",
"Láďa Štětka",
"Já potřebuji černochy!",
"Není černoch jako černoch!",
"Srdíčka!",
"Samova kláda",
"Kočička v nesnázích",
"Jedu na koni, jó do města...",
"Milada Mastná",
"Bedřich Kulíšek",
"Adri nikdy nespí!",
"Špínova koule",
"Jsi divná, zemři!",
"Já jsem autobus, já jsem na konečné!",
"Houby jsou maso lesa!",
"Rusofilka",
"Sam zpitý pod obraz",
"Štrůdl",
"Kladivem tu vládnu já!",
"Krysí čaj",
"Život je jako pes s otěžemi!",
"Kostel!",
"Přestaň s tím, vyhledej pomoc!",
"Útok draka Šmaka",
"Rodinka",
"Punčová vila",
"sebepřekonávání",
"Nemám kalhoty. Chcete půjčit? (Půjčování kalhot)",
"Hotelem neprojdete!",
"Čistič",
"Silná, nezávislá žena, která nepotřebuje kouřit",
"Hitler",
"Campari",
"Jěštěrušky",
"(U Černého vlka?) Není to vlk, je to houba!",
"Tyčka",
"Je naprosto nezbytné!",
"Lukáš má vždycky pravdu!",
"Žumpa",
"ježek Kazimír",
"Kdybys byla mladší, tak bych si tě vzal.",
"Ostrov Marie Majerové",
"Hafík Hasan",
"Čoveče, ty seš nějakej horkokrevnej. Si tě vezmu domů, abys mi to tam vytopil!",
"Václava Kocián",
"Josef Václav Housenka",
"A bude tam ten průmysl?",
"Katolická mládež",
"Patryka",
"Krmení",
"Tak seš blbá!",
"Normalizujme domácí násilí!",
"Omlouvám se za svůj pedagogický tón!",
"Macháček",
"Billa košík",
"Nejlepší hodina chemie",
"Ryba",
"Vánoční putování (v tercii sbírání odpadků)",
"Fakt fajn kurva",
"Tohle je kamarádské/přátelské selhání",
"Snapchata",
"Redditrt",
"Haf/Štěk",
"Kys. citronová",
"Prohrál jsem!",
"outfit dýně",
"A dost!",
"Máš problém?",
"Mládeži!",
"Metabolismus",
"Fantomas",
"Prosím jedny mravence na stromě s kečupem a bez hub!",
"Čokoládka punčovka",
"Saša",
"Samův soused",
"Borisi!",
"Sochy ožívají!",
"Tryskomyš",
"Pjůr chemie/chechemie",
"Plochá dráha",
"Kolík",
"[Saaam, bite, ajn apfl... Majn líbr... Majn fírer]; Saaam, ich möchte einen Apfel...                 Meine Liebe...                                                    Mein Führer...",
"Rakovina hrtanu",
"Alžbětka",
"Adri je heterosexuál, Adri: Odkdy?",
"Šubyduby amerika",
"Ejakulační plán",
"Adri se mnou zase nemluví!",
"Dicky za váš Dick!",
"Já tě zbuším!",
"Moment!",
"Nikyta",
"Skandinavia, eh, eh\nWaka waka, eh, eh\nSkandinavia Skandinavia\nThis time for Africa",
"Fakt fajn komár",
"Křížové výpravy",
"Kočkopes",
"You hate McCartney without knowing!           He stop Lenonkook leaving the group!",
"Jelda pracuje pro KGB!",
"Tři, dva, teď - a páru, a páru\nTři dva, teď!",
"Co se stane když oře posypeme křemíkem? Silikoň",
"Buzerant",
"Humřít!",
"Extázka",
"Svoboda je privilegium!",
"Hobit Vojta",
"Ty ptáku stěhovavý!",
"Buď tak pyramidálně pompézní a vynechávej řádky!",
"Vytáhněte si pravítka! Půjdeme měřit! Ale nebojte chlapci... Jenom mince!",
"Mamča",
"Už nepij, kámo!",
"Protože je ryba ryba (ŠŤASTNÁ!)",
"(Víš, co říkáš bráškovi?) Nepodceňuj se!",
"Já jsem revoluční!",
"Já mám Hláďo!",
"Mandelinka Bramborová - americký brouk!",
"To se vsákne!",
"Pojďme si říct, že to je hezké!"
]


var counter = 0;

function shuffleArray() {
    cardArray.sort(() => Math.random() - 0.5);
}
shuffleArray();

document.getElementById('button').onclick = function() {
    counter += 1;
    if (counter > cardArray.length) {
        counter = 0;
        shuffleArray();
    }
    document.getElementById("card").innerHTML = cardArray[counter];
    var random = Math.round(Math.random());
    if (random === 0) {
        console.log("hi");
        document.getElementById("cinost").innerHTML = "Pantomima";
    } else if (random === 1) {
        document.getElementById("cinost").innerHTML = "Popis";
    }
};