var cardArray = [  
"Skříplotina",
"Máslo komplikuje život!",
"A budeš/me se brodit v botech?",
"Incest",
"Šlápnutí na slimáka",
"Hlavně nebreč!",
"Byla jsem tu rychlejc než vy!",
"Pohlazení přes očičko",
"Skřetí běh",
"Jedině destiláty!",
"Výstřik do neznáma",
"Pojď se podívat na pavučinku!",
"Víte, co se stane, když okurka spadne do jámy?",
"Cítím se jako netopýří princezna!",
"Hele klokan a je bílej!",
"Já jsem kanadský ninja!",
"Myš Lenka",
"Hele poryv!",
"Láďa Štětka ",
"Já potřebuji černochy!",
"Není černoch jako černoch!",
"Srdíčka!",
"Samova kláda",
"Kočička v nesnázích/depresích ",
"To jsou pěsti plné hněvu!",
"Milada Mastná",
"Bedřich Kulíšek",
"Adri nikdy nespí!",
"Špínova koule",
"Jsi divná, zemři!",
"Já jsem autobus, já jsem na konečné!",
"Houby jsou maso lesa!",
"Kebaby",
"Sam opitý pod obraz(em)",
"Štrůdl",
"Kladivem tu vládnu já!",
"Krysí čaj ",
"Život je jako pes s otěžemi!",
"Kostel!",
"Přestaň s tím, vyhledej pomoc!",
"Útok draka Šmaka",
"Rodinka",
"Punčová vila",
"sebepřekonávání ",
"Nemám kalhoty. Chcete půjčit? (Půjčování kalhot)",
"Hotelem neprojdete! ",
"Čistič ",
"Silná, nezávislá žena, která nepotřebuje kouřit",
"Hitler",
"Campari",
"Jěštěrušky",
"(U Černého vlka) Není to vlk, je to houba!",
"Tyčka ",
"Je naprosto nezbytné!",
"Lukáš má vždycky pravdu!",
"Žumpa",
"ježek Kazimír",
"Kdybys byla mladší, tak bych si tě vzal.",
"Ostrov Marie Majerové",
"Hafík Hasan",
"Čoveče, ty seš nějakej horkokrevnej.\nSi tě vezmu domů, abys mi to tam vytopil!",
"Václava Kocián",
"Josef Václav Housenka",
"A bude tam ten průmysl?",
"Katolická mládež",
"Patryka",
"Krmení",
"Tak seš blbá!",
"Normalizujme domácí násilí!",
"Omlouvám se za svůj pedagogický tón!",
"Macháček",
"Billa košík",
"Nejlepší hodina chemie",
"Ryba",
"Vánoční putování\n(a v tercii sbírání odpadků)",
"Fakt fajn kurva ",
"Tohle je kamarádské/přátelské selhání",
"Snapchata",
"Redditrt",
"Haf/Štěk ",
"Kys. citronová ",
"Prohrál jsem!",
"outfit dýně ",
"A dost!",
"Máš problém?",
"Mládeži!",
"Metabolismus ",
"Fantomas",
"Prosím jedny mravence na stromě\ns kečupem a bez hub! ",
"Čokoládka punčovka",
"Saša",
"Samův soused",
"Borisi!",
"Sochy ožívají!",
"Tryskomyš ",
"Pjůr chemie/chechemie",
"Plochá dráha",
"Kolík ",
"[Saaam, bite, ajn apfl...\nMajn líbr... Majn fírer];\nSaaam, ich möchte einen Apfel...\nMeine Liebe...\nMein Führer...",
"Rakovina hrtanu",
"Alžbětka",
"Adri je heterosexuál, Adri: Odkdy?",
"Šubyduby amerika",
"Ejakulační plán",
"Adri se mnou zase nemluví!",
"Moc Dicky za váš Dick!",
"Já tě zbuším!",
"Moment!",
"Nikyta",
"Skandinavia, eh, eh\nWaka waka, eh, eh\nSkandinavia Skandinavia\nThis time for Africa",
"Fakt fajn komár",
"Křížové výpravy ",
"Kočkopes",
"You hate McCartney without knowing!\nHe stop Lenonkook leaving the group!",
"Jelda pracuje pro KGB!",
"Tři, dva, teď - a páru, a páru",
"dva, teď!",
"Co se stane když oře posypeme křemíkem?\nSilikoň",
"Buzerant",
"Humřít!",
"Extázka ",
"Svoboda je privilegium!",
"Hobit Vojta ",
"Ty ptáku stěhovavý!",
"Buď tak pyramidálně pompézní a vynechávej řádky!",
"Vytáhněte si pravítka! Půjdeme měřit!\nAle nebojte chlapci... Jenom mince!",
"Mamča",
"Už nepij, kámo!",
"Protože je ryba ryba (ŠŤASTNÁ!)",
"(Víš, co říkáš bráškovi?) Nepodceňuj se!",
"Já jsem revoluční!",
"Já mám Hláďo!",
"Mandelinka Bramborová - americký brouk!",
"To se vsákne!",
"Pojďme si říct, že to je hezké!",
"olůvko (nějaká sračka na chytání ryb)",
"Staň se veganem Dubínku!",
"Proč se držíte za ruce?",
"Je tu nějak mrtvo!",
"Ty hade! ",
"Je to ale syčák! ",
"Chleba! (Chlebík!)",
"Martinovy kozy",
"Martinova (špinavá) díra ",
"Ausfahrt ",
"Strč si celou cyklistiku do prdele řidítkama napřed!",
"Ikeja",
"vídeňská kavka",
"Geologie není věda! ",
"Tady vidim velký špatný!",
"Ich Bin Schnappi das kleine Krokodil!",
"luštění křížovek ",
"Mrdá mi v hlavě, mrdá mi v hlavě!",
"Kull Wahád - "Jsem hluboce vzrušen!"",
"Samvěd Křepelka",
"Tři prsteny pro krále elfů pod nebem,\nSedm vládcům trpaslíků v síních z kamene,\nDevět mužům: každý je k smrti odsouzen,\nJeden pro Temného pána, jenž dlí na trůně\nv zemi Mordor, kde se snoubí šero se šerem.\nJeden prsten vládne všem, Jeden jim všem káže,\nJeden všechny přivede, do temnoty sváže\nv zemi Mordor, kde se snoubí šero se šerem.",
" Písek! (Písecká fůrie!)",
"Dát okurku za kočku",
"Ty můro jedna pelešivá!",
"Semrád o Vánocích!",
"Pepek",
"Mládeži!"
];


var counter = 0;

function shuffleArray() {
    cardArray.sort(() => Math.random() - 0.5);
}
shuffleArray();

document.getElementById('button').onclick = function() {
    counter += 1;
    if (counter > cardArray.length) {
        counter = 0;
        shuffleArray();
    }
    document.getElementById("card").innerHTML = cardArray[counter];
    var random = Math.round(Math.random());
    if (random === 0) {
        console.log("hi");
        document.getElementById("cinost").innerHTML = "Pantomima";
        document.getElementByName("body").style.backgroundColor = "blue";
    } else if (random === 1) {
        document.getElementById("cinost").innerHTML = "Popis";
        document.getElementByName("body").style.backgroundColor = "red";
    }
};
